services:
  - type: web
    name: agendaLab
    env: python
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 3 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false